export {default as Hero} from './Hero.jsx'
export {default as About} from './About.jsx'
export {default as Slide} from './Slide.jsx'
export {default as Values} from './Values.jsx'
export {default as Footer} from './Footer.jsx'
